// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9zSQAWL1IXG_2H8-x9s7I49ocAYjmTOk',
    appId: '1:449680673384:web:7b7f1006eede9760d5c9dd',
    messagingSenderId: '449680673384',
    projectId: 'ecom1np',
    authDomain: 'ecom1np.firebaseapp.com',
    storageBucket: 'ecom1np.firebasestorage.app',
    measurementId: 'G-W99G0F7LQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD88OZioaalbyOoqlJwbsfzInLiSchPDeE',
    appId: '1:449680673384:android:429e7d30ca63832ad5c9dd',
    messagingSenderId: '449680673384',
    projectId: 'ecom1np',
    storageBucket: 'ecom1np.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj1cD240MINuYfJOjOravA60q7OMEN0ys',
    appId: '1:449680673384:ios:60b081e8f0f038bfd5c9dd',
    messagingSenderId: '449680673384',
    projectId: 'ecom1np',
    storageBucket: 'ecom1np.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj1cD240MINuYfJOjOravA60q7OMEN0ys',
    appId: '1:449680673384:ios:60b081e8f0f038bfd5c9dd',
    messagingSenderId: '449680673384',
    projectId: 'ecom1np',
    storageBucket: 'ecom1np.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9zSQAWL1IXG_2H8-x9s7I49ocAYjmTOk',
    appId: '1:449680673384:web:853fb549350dab6cd5c9dd',
    messagingSenderId: '449680673384',
    projectId: 'ecom1np',
    authDomain: 'ecom1np.firebaseapp.com',
    storageBucket: 'ecom1np.firebasestorage.app',
    measurementId: 'G-95KE1MRR28',
  );
}